spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
application:
  security:
    jwt:
      expiration: ${EXPIRATION}
      secret-key: ${SECRET_KEY}

